name: build

on:
  pull_request:
    paths: &paths
      - 'config/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'
  push:
    branches: ['master']
    paths: *paths

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  phpunit:
    name: phpunit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build
        working-directory: ./tests
        run: docker compose build
      - name: PHP Unit tests coverage
        working-directory: ./tests
        run: docker compose run --rm php-cli vendor/bin/phpunit --coverage-clover ./tests/runtime/coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          verbose: true
          files: ./tests/runtime/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
