name: mutation test

on:
  pull_request:
    paths: &paths
      - 'config/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/mutation.yml'
      - 'composer.json'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'
  push:
    branches: ['master']
    paths: *paths

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  mutation:
    name: mutation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Mutation tests
        run: make mutation
